server:
  port: ${GATEWAY_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST_NAME}:${EUREKA_SERVER_PORT}/eureka/